#! /bin/bash
# Prepend a file's name to itself as a Markdown title
# R.R.T.   26/12/05; converted from smut to Markdown 14/5/17
# Usage: entitle FILE...

if [ $# -lt 1 ]; then
    echo Usage: `basename $0` FILE...
    exit 1
fi

for i; do
    title=`basename "$i"`
    echo -e "# $title\n\n" | prepend "$i"
done
